# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1390, 792)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1301, 711))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.uploadTab = QtGui.QWidget()
        self.uploadTab.setObjectName(_fromUtf8("uploadTab"))
        self.nextButton1 = QtGui.QPushButton(self.uploadTab)
        self.nextButton1.setGeometry(QtCore.QRect(1110, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nextButton1.setFont(font)
        self.nextButton1.setObjectName(_fromUtf8("nextButton1"))
        self.uploadButton = QtGui.QPushButton(self.uploadTab)
        self.uploadButton.setGeometry(QtCore.QRect(590, 0, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName(_fromUtf8("uploadButton"))
        self.fileUploadText = QtGui.QLabel(self.uploadTab)
        self.fileUploadText.setGeometry(QtCore.QRect(360, 210, 561, 16))
        self.fileUploadText.setText(_fromUtf8(""))
        self.fileUploadText.setObjectName(_fromUtf8("fileUploadText"))
        self.inputDataLabel = QtGui.QLabel(self.uploadTab)
        self.inputDataLabel.setGeometry(QtCore.QRect(610, 200, 51, 21))
        self.inputDataLabel.setText(_fromUtf8(""))
        self.inputDataLabel.setObjectName(_fromUtf8("inputDataLabel"))
        self.tabWidget.addTab(self.uploadTab, _fromUtf8(""))
        self.preprocessTab = QtGui.QWidget()
        self.preprocessTab.setObjectName(_fromUtf8("preprocessTab"))
        self.nextButton2 = QtGui.QPushButton(self.preprocessTab)
        self.nextButton2.setGeometry(QtCore.QRect(1110, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nextButton2.setFont(font)
        self.nextButton2.setObjectName(_fromUtf8("nextButton2"))
        self.filterButton = QtGui.QPushButton(self.preprocessTab)
        self.filterButton.setGeometry(QtCore.QRect(630, 257, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.filterButton.setFont(font)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.lineEdit = QtGui.QLineEdit(self.preprocessTab)
        self.lineEdit.setGeometry(QtCore.QRect(410, 270, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.filterText = QtGui.QLabel(self.preprocessTab)
        self.filterText.setGeometry(QtCore.QRect(450, 400, 371, 51))
        self.filterText.setText(_fromUtf8(""))
        self.filterText.setObjectName(_fromUtf8("filterText"))
        self.tabWidget.addTab(self.preprocessTab, _fromUtf8(""))
        self.algorithmTab = QtGui.QWidget()
        self.algorithmTab.setObjectName(_fromUtf8("algorithmTab"))
        self.nextButton3 = QtGui.QPushButton(self.algorithmTab)
        self.nextButton3.setGeometry(QtCore.QRect(1110, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nextButton3.setFont(font)
        self.nextButton3.setObjectName(_fromUtf8("nextButton3"))
        self.runAlgorithmButton = QtGui.QPushButton(self.algorithmTab)
        self.runAlgorithmButton.setGeometry(QtCore.QRect(470, 230, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.runAlgorithmButton.setFont(font)
        self.runAlgorithmButton.setObjectName(_fromUtf8("runAlgorithmButton"))
        self.algorithmText = QtGui.QLabel(self.algorithmTab)
        self.algorithmText.setGeometry(QtCore.QRect(560, 430, 191, 20))
        self.algorithmText.setText(_fromUtf8(""))
        self.algorithmText.setObjectName(_fromUtf8("algorithmText"))
        self.progressBar = QtGui.QProgressBar(self.algorithmTab)
        self.progressBar.setGeometry(QtCore.QRect(530, 340, 181, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.tabWidget.addTab(self.algorithmTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.homeButton = QtGui.QPushButton(self.outputTab)
        self.homeButton.setGeometry(QtCore.QRect(1110, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName(_fromUtf8("homeButton"))
        self.outputLabel = QtGui.QLabel(self.outputTab)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 1241, 511))
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.tabWidget.addTab(self.outputTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1390, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.nextButton1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Move to the next screen</p></body></html>", None))
        self.nextButton1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Move to the next screen</p></body></html>", None))
        self.nextButton1.setText(_translate("MainWindow", "Next", None))
        self.uploadButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click here to upload a .csv file!</p></body></html>", None))
        self.uploadButton.setText(_translate("MainWindow", "Upload File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uploadTab), _translate("MainWindow", "Upload", None))
        self.nextButton2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Move to the next page</p></body></html>", None))
        self.nextButton2.setText(_translate("MainWindow", "Next", None))
        self.filterButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click here to filter data based on your input.</p></body></html>", None))
        self.filterButton.setText(_translate("MainWindow", "Filter", None))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter a value to remove from the data set. All records with this value will be purged.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessTab), _translate("MainWindow", "Preprocess", None))
        self.nextButton3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Move to the next screen</p><p><br/></p></body></html>", None))
        self.nextButton3.setText(_translate("MainWindow", "Next", None))
        self.runAlgorithmButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Run the decision tree on your data.</p></body></html>", None))
        self.runAlgorithmButton.setText(_translate("MainWindow", "Run Decision Tree", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithmTab), _translate("MainWindow", "Algorithm", None))
        self.homeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go back home</p></body></html>", None))
        self.homeButton.setText(_translate("MainWindow", "Home", None))
        self.outputLabel.setText(_translate("MainWindow", "Output", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), _translate("MainWindow", "Ouput", None))

